### ISSUE TITLE
Ubuntu 22

### ISSUE THREAD

**Issue by swa2050** [rajannpatel/ubuntupbx#5] opened 2023-01-17 10:10 UTC
![22](https://user-images.githubusercontent.com/122435442/212870453-154a74e4-fb33-47a1-a120-1f2674badc69.JPG)

I Face error during installation

**Comment by rajannpatel** [comment] 2023-02-06 23:52
This is a duplicate of https://github.com/rajannpatel/ubuntupbx/issues/3

The resolution was found, the install.sh script has been updated 3 weeks ago with commit b4e3f8012de92e7d266e83936e4e5c4a4390aefb. I am unable to reproduce this issue on a LXD container or on a public cloud virtual machine.

Please reopen issue #3 if you continue having issues.

**Closed by rajannpatel** 2023-02-06 23:52 UTC

**Comment by rajannpatel** [comment] 2023-02-06 23:55
https://github.com/rajannpatel/ubuntupbx/blob/main/jammy/install.sh
