### ISSUE TITLE
UBUNTU 20

### ISSUE THREAD

**Issue by swa2050** [rajannpatel/ubuntupbx#4] opened 2023-01-17 10:10 UTC
![20](https://user-images.githubusercontent.com/122435442/212870342-4c328d9d-70db-4e09-9e68-401f70aabd11.JPG)

I Face error during installation

**Comment by rajannpatel** [comment] 2023-02-06 23:53
This is a duplicate of https://github.com/rajannpatel/ubuntupbx/issues/2

The resolution was found, the install.sh script has been updated 3 weeks ago with commit b4e3f8012de92e7d266e83936e4e5c4a4390aefb. I am unable to reproduce this issue on a LXD container or on a public cloud virtual machine.

Please reopen issue #2 if you continue having issues.

**Closed by rajannpatel** 2023-02-06 23:53 UTC

**Comment by rajannpatel** [comment] 2023-02-06 23:56
The latest https://github.com/rajannpatel/ubuntupbx/blob/main/focal/install.sh does not have this issue

**Comment by swa2050** [comment] 2023-02-07 06:17
![image](https://user-images.githubusercontent.com/122435442/217163740-4f8ff9b4-f810-4cf8-96e2-3c7ececd1ca3.png)

still have same in focal version

**Comment by rajannpatel** [comment] 2023-02-07 10:25
Line 25 in the install.sh script reads: `DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs npm`. This should install NodeJS, I'm surprised to see in the screenshot that NodeJS version 8 or higher is not installed. I'm thinking of refactoring install.sh to trigger the cloud-init.yaml file instead, so we can use the logging capabilities of cloud-init to debug issues like these
